name: hpdm209z
channels:
  - conda-forge
dependencies:
  - contextily=1.6.0
  - folium=0.17.0
  - geopandas=1.0.1
  - geoplot=0.5.1
  - ipywidgets=8.1.7
  - joblib=1.4.2
  - jupyterlab=4.4.7
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.9.1
  - numpy=2.0.1
  - pandas=2.2.2
  - pip=24.0
  - plotly=6.5.2
  - pmdarima=2.0.4
  - pysal=23.7
  - python=3.11
  - scipy=1.14.0
  - seaborn=0.13.2
  - scikit-learn=1.5.1
  - simpy=4.1.1
  - sim-tools=1.0.3
  - statsmodels=0.14.2
  - pip:
    - tensorflow-cpu==2.15.0
    - prophet==1.1.5
    - forecast-tools==0.4.1

